//
//  Copyright (C) 2012-2025, Duzy Chan <code@extbit.io>, all rights reserverd.
//  Use of this source code is governed by a BSD-style license that can be
//  found in the LICENSE file.
//
//go:build checkpoints

package smart

import (
	"sort"
	"strings"
	"regexp"
)

var rxLC = regexp.MustCompile(`[0-9]+:[0-9]+:?`)
var rxSquareBracket = regexp.MustCompile(`\[?(.+?)\]?`)

// NOTE: cannot decalre `checkpoints` as `const` because it's compile-time evaled.
var checkpoints = true // vertag != "final"

var check_prefix_specs = map[string]map[string]map[string]string{
	"p:testdata/value/13": prefix_value_13,
	"p:testdata/builtins/addprefix": prefix__addprefix,
	"p:testdata/builtins/addsuffix": prefix__addsuffix,
	"s:testdata/value/13": suffix_value_13,
	"s:testdata/builtins/addprefix": suffix__addprefix,
	"s:testdata/builtins/addsuffix": suffix__addsuffix,
}
func check_prefix(ctx Context, tag string, x, y Value, res *Value) {
	if j := _project(ctx); j == nil {
		if false {
			var s = try[string](ctx, source{})
			debug(pc(pc(ctx,y),x), "nil project | %s %v %v %v", s, ts(x), ts(y), ts(*res), trace{})
		}
	} else if spec, ok := check_prefix_specs[tag+":"+j.spec]; ok {
		var (
			src = strings.Split(try[string](ctx,source{}),":")
			xy = func() (s string) {
				if src[0] != "loader.go" { s = src[1] + " " }
				return s+ts(x)+" "+ts(y)
			} ()
			vs = spec[src[0]][xy]
		)
		if rs := (*res).String()+" "+ts(*res); vs == "" {
			debug(pc(pc(ctx,y),x), "`%v`:`%s`,", xy, rs, trace{})
		} else if rs != vs {
			debug(pc(pc(ctx,y),x), _f("`%v`", xy), _f(`got: %s`, rs), _f(`!= : %s`, vs), trace{})
		}
	}
}

type sorted_strings []string

var checkspecs = map[string]map[string]map[string]any{
	"testdata/assert":               checkpoints__assert,
	"testdata/locals":               checkpoints__locals,
	"testdata/builtins/addprefix":   checkpoints__addprefix,
	"testdata/builtins/addsuffix":   checkpoints__addsuffix,
	"testdata/builtins/trimprefix":  checkpoints__trimprefix,
	"testdata/builtins/trimsuffix":  checkpoints__trimsuffix,
	"testdata/builtins/if":          checkpoints__if,
	"testdata/builtins/foreach":     checkpoints__foreach,
	"testdata/builtins/foreach/1":   checkpoints__foreach1,
	"testdata/builtins/foreach/2":   checkpoints__foreach2,
	"testdata/builtins/foreach/3":   checkpoints__foreach3,
	"testdata/builtins/foreach/4":   checkpoints__foreach4,
	"testdata/builtins/foreach/5":   checkpoints__foreach5,
	"testdata/builtins/wildcard":    checkpoints__wildcard,
	"testdata/builtins/wildcard/1":  checkpoints__wildcard1,
	"testdata/builtins/wildcard/2":  checkpoints__wildcard2,
	"testdata/builtins/wildcard/3":  checkpoints__wildcard3,
	"testdata/builtins/closure":     checkpoints__closure,
	"testdata/builtins/delegate":    checkpoints__delegate,
	"testdata/builtins/logic":       checkpoints__logic,
	"testdata/builtins/contains":    checkpoints__contains,
	"testdata/builtins/join":        checkpoints__join,
	"testdata/builtins/xor":         checkpoints__xor,
	"testdata/builtins/or":          checkpoints__or,
	"testdata/value":                checkpoints_value,
	"testdata/value/auto":           checkpoints_value_auto,
	"testdata/value/closure":        checkpoints_value_closure,
	"testdata/value/disjunction":    checkpoints_value_disjunction,
	"testdata/value/placeholder":    checkpoints_value_placeholder,
	"testdata/value/optional":       checkpoints_value_optional,
	"testdata/value/optional/foo":   checkpoints_value_optional_foo,
	"testdata/value/glob":           checkpoints_value_glob,
	"testdata/value/1":              checkpoints_value_1,
	"testdata/value/2/0":            checkpoints_value_20,
	"testdata/value/2/1":            checkpoints_value_21,
	"testdata/value/2/2":            checkpoints_value_22,
	"testdata/value/3":              checkpoints_value_3,
	"testdata/value/4":              checkpoints_value_4,
	"testdata/value/5":              checkpoints_value_5,
	"testdata/value/6":              checkpoints_value_6,
	"testdata/value/7":              checkpoints_value_7,
	"testdata/value/8":              checkpoints_value_8,
	"testdata/value/9":              checkpoints_value_9,
	"testdata/value/10":             checkpoints_value_10,
	"testdata/value/11":             checkpoints_value_11,
	"testdata/value/12":             checkpoints_value_12,
	"testdata/value/13":             checkpoints_value_13,
	"testdata/value/bug_01":         checkpoints_value_bug_01,
	"testdata/valcache":             checkpoints_valcache,
	"testdata/valcache/1":           checkpoints_valcache1,
	"testdata/valcache/2":           checkpoints_valcache2,
	"testdata/valcache/3":           checkpoints_valcache3,
	"testdata/rule/shell/for-stdout":checkpoints_rule_shell_forstdout,
	"testdata/template":             checkpoints_template,
	"testdata/modifier":             checkpoints_modifiers,
}
func check(ctx Context, res Value, p Value, x ...Value) {
	var src = strings.Split(try[string](ctx,source{}), ":")
	if src == nil || (len(src) == 1 && src[0] == "") {
		if true {
			switch p.String() {
			case "test.paniconexit0", "test.timeout": // TODO: fix these strange value
				if false { debug(pc(ctx,p), "TODO: check(%v %v %v)", p, res, x, trace{}) }
			default:
				if false { debug(pc(ctx,p), "check(%v %v %v)", p, res, x) }
			}
		}
		return
	}

	var (
		spec string
		d, _ = do(ctx, origin_def{}).(*def)
		dn = func() (s string) { if d != nil { s = d.name }; return } ()
		ks = func() (s string) {
			if 2 == len(src) { if src[0] != "loader.go" { s = src[1] + " " }}
			if d != nil { s += line_column(d)+":" }
			if dn != "" { s += dn + " "  }
			s += p.String()+" "+ts(p)
			return
		} ()
		tr = func() (a any) {
			if spec == "" { if j := _project(ctx); j != nil { spec = j.spec } }
			return checkspecs[spec][src[0]][ks]
		} ()
		vs = func() (s string) {
			switch t := tr.(type) {
			case sorted_strings:
				if l, ok := res.(*list); ok {
					sort.Slice(l.elems, func(i, j int) bool {
						return l.elems[i].String() < l.elems[j].String()
					})
					tr = []string(t)
				}
			}
			s += res.String()+" "+ts(res,ctx)
			return
		} ()
	)
	switch v := tr.(type) {
	case   string:                       if v == vs { /* delete(checkspecs[spec][src[0]],ks); */ return }
	case []string: for _, s := range v { if s == vs { /* delete(checkspecs[spec][src[0]],ks); */ return } }
	case nil:
		if src == nil {
			debug(pc(ctx,p), _f("`%v`:`%s`,", ks, vs), trace{})
		} else {
			debug(pc(ctx,p), _f("src=%s p=%v", src, p), _f("`%v`:`%s`,", ks, vs), trace{})
		}
		return
	}
	debug(pc(ctx,p), _f("`%v`", ks), _f(`got: %s`, vs), _f(`!= : %v`, tr), trace{})
}

var checkstrs = map[string]map[string]map[string]any{
	"testdata/assert":               checkstrs__assert,
	"testdata/locals":               checkstrs__locals,
	"testdata/builtins/addprefix":   checkstrs__addprefix,
	"testdata/builtins/addsuffix":   checkstrs__addsuffix,
	"testdata/builtins/trimprefix":  checkstrs__trimprefix,
	"testdata/builtins/trimsuffix":  checkstrs__trimsuffix,
	"testdata/builtins/if":          checkstrs__if,
	"testdata/builtins/foreach":     checkstrs__foreach,
	"testdata/builtins/foreach/1":   checkstrs__foreach1,
	"testdata/builtins/foreach/2":   checkstrs__foreach2,
	"testdata/builtins/foreach/3":   checkstrs__foreach3,
	"testdata/builtins/foreach/4":   checkstrs__foreach4,
	"testdata/builtins/foreach/5":   checkstrs__foreach5,
	"testdata/builtins/wildcard":    checkstrs__wildcard,
	"testdata/builtins/wildcard/1":  checkstrs__wildcard1,
	"testdata/builtins/wildcard/2":  checkstrs__wildcard2,
	"testdata/builtins/wildcard/3":  checkstrs__wildcard3,
	"testdata/builtins/closure":     checkstrs__closure,
	"testdata/builtins/delegate":    checkstrs__delegate,
	"testdata/builtins/logic":       checkstrs__logic,
	"testdata/builtins/contains":    checkstrs__contains,
	"testdata/builtins/join":        checkstrs__join,
	"testdata/builtins/xor":         checkstrs__xor,
	"testdata/builtins/or":          checkstrs__or,
	"testdata/value":                checkstrs_value,
	"testdata/value/auto":           checkstrs_value_auto,
	"testdata/value/closure":        checkstrs_value_closure,
	"testdata/value/disjunction":    checkstrs_value_disjunction,
	"testdata/value/placeholder":    checkstrs_value_placeholder,
	"testdata/value/optional":       checkstrs_value_optional,
	"testdata/value/optional/foo":   checkstrs_value_optional_foo,
	"testdata/value/glob":           checkstrs_value_glob,
	"testdata/value/1":              checkstrs_value_1,
	"testdata/value/2/0":            checkstrs_value_20,
	"testdata/value/2/1":            checkstrs_value_21,
	"testdata/value/2/2":            checkstrs_value_22,
	"testdata/value/3":              checkstrs_value_3,
	"testdata/value/4":              checkstrs_value_4,
	"testdata/value/5":              checkstrs_value_5,
	"testdata/value/6":              checkstrs_value_6,
	"testdata/value/7":              checkstrs_value_7,
	"testdata/value/8":              checkstrs_value_8,
	"testdata/value/9":              checkstrs_value_9,
	"testdata/value/10":             checkstrs_value_10,
	"testdata/value/11":             checkstrs_value_11,
	"testdata/value/12":             checkstrs_value_12,
	"testdata/value/13":             checkstrs_value_13,
	"testdata/value/bug_01":         checkstrs_value_bug_01,
	"testdata/rule/shell/for-stdout":checkstrs_rule_shell_forstdout,
	"testdata/template":             checkstrs_template,
	"testdata/modifier":             checkstrs_modifiers,
	"testdata/valcache":             checkstrs_valcache,
	"testdata/valcache/1":           checkstrs_valcache1,
	"testdata/valcache/2":           checkstrs_valcache2,
	"testdata/valcache/3":           checkstrs_valcache3,
}
func check_string(ctx Context, p Value, v Value, res string) {
	var (
		src = strings.Split(try[string](ctx,source{}),":")
		d, _ = do(ctx, origin_def{}).(*def)
		dn = func() (s string) { if d != nil { s = d.name }; return } ()
		ks = func() (s string) {
		if src[0] != "loader.go" && 1 < len(src) { s = src[1] + " " }
			s += line_column(d)+":"+dn+" "+p.String()+" "+ts(p)
			return
		} ()
		vs = ts(v,ctx)+" "+res
		ta = checkstrs[_project(ctx).spec][src[0]][ks]
	)
	switch v := ta.(type) {
	case []string: for _, s := range v { if s == vs { return } }
	case   string:                       if v == vs { return }
	case nil: debug(pc(ctx,p), "`%v`:`%s`,", ks, vs, trace{})
	}
	debug(pc(ctx,p), _f("`%v`", ks),
		_f(`got: %s`, vs),
		_f(`!= : %v`, ta),
		_f(`val: %v`, v),
		_f(`res: %v`, res),
		trace{})
}

var checkpoints_cmp = map[string]string{
	`[{= {=flag {=word foo}}} {=word bar}] [{=flag {=word foobar}}] []`:`equal`,
	`[{= {=flag {=word foo}}} {=word bar}] {=flag {=word foobar}} []`:`equal`,
	`[{= {=flag {=}}} {=word foobar}] {=flag {=word foobar}} []`:`equal`,
	`[{= {=word foo}}] [{=word foo}] []`:`equal`,
	`[{= {=word foo}}] {=list {=word foo}} []`:`equal`,
	`[{=compound {= {=flag {=word foo}}} {=word bar}}] [{=flag {=word foobar}}] []`:`equal`,
	`[{=compound {= {=flag {=word foo}}} {=word bar}}] {=list {=flag {=word foobar}}} []`:`equal`,
	`[{=compound {= {=flag {=}}} {=word foobar}}] [{=flag {=word foobar}}] []`:`equal`,
	`[{=compound {= {=flag {=}}} {=word foobar}}] {=list {=flag {=word foobar}}} []`:`equal`,
	`[{=flag {=word foobar}}] [{=compound {= {=flag {=word foo}}} {=word bar}}] []`:`equal`,
	`[{=flag {=word foobar}}] [{=compound {= {=flag {=}}} {=word foobar}}] []`:`equal`,
	`[{=flag {=word foobar}}] {=list {=compound {= {=flag {=word foo}}} {=word bar}}} []`:`equal`,
	`[{=flag {=word foobar}}] {=list {=compound {= {=flag {=}}} {=word foobar}}} []`:`equal`,
	`[{=meta **} {=punct .} {=word def} {=punct .} {=word am}] [{=word foobar} {=word config} {=glob {=meta *} {=punct .} {=word def} {=punct .} {=word am}}] []`:`smaller`,
	`[{=meta **} {=punct .} {=word h}] [{=meta **} {=punct .} {=word h}] []`:`equal`,
	`[{=meta **} {=punct .} {=word h}] [{=meta *} {=punct .} {=word h}] []`:`greater`,
	`[{=meta **} {=punct .} {=word h}] {=glob {=meta **} {=punct .} {=word h}} []`:`equal`,
	`[{=meta **} {=punct .} {=word h}] {=path {=glob {=word foo} {=meta ?} {=meta ?} {=meta ?}} {=compound {=word x} {=punct .} {=word h}}} []`:`greater`,
	`[{=meta **} {=punct .} {=word h}] {=path {=word foo} {=glob {=meta *} {=punct .} {=word h}}} []`:`greater`,
	`[{=meta **} {=punct .} {=word h}] {=path {=word foo} {=word bar} {=glob {=word v} {=meta ?} {=punct .} {=word h}}} []`:`greater`,
	`[{=meta *} {=punct .} {=word h}] [{=meta **} {=punct .} {=word h}] []`:`smaller`,
	`[{=meta *} {=punct .} {=word h}] {=glob {=meta **} {=punct .} {=word h}} []`:`smaller`,
	`[{=meta *} {=punct .} {=word h}] {=glob {=meta *} {=punct .} {=word h}} []`:`equal`,
	`[{=punct .} {=word test}] [{=string .test}] []`:`equal`,
	`[{=punct .} {=word test}] {=compound {=punct .} {=word test}} []`:`equal`,
	`[{=punct .} {=word test}] {=string .test} []`:`equal`,
	`[{=token **}] {=glob {=word foo} {=meta ?} {=meta ?} {=meta ?}} []`:`greater`,
	`[{=token .} {=string test}] [{=string .test}] []`:`equal`,
	`[{=token .}] {=compound {=word bar} {=punct .} {=word c}} []`:`smaller`,
	`[{=word foobar} {=word config} {=glob {=meta *} {=punct .} {=word def} {=punct .} {=word am}}] {=glob {=meta **} {=punct .} {=word def} {=punct .} {=word am}} []`:`smaller`,
	`[{=word foo} {=glob {=meta *} {=punct .} {=word h}}] {=path {=word foo} {=glob {=meta *} {=punct .} {=word h}}} []`:`equal`,
	`[{=word x} {=punct .} {=word h}] [{=string config}] []`:`greater`,
	`[{=word x} {=punct .} {=word h}] [{=string x.h}] []`:`equal`,
	`[{=word x} {=punct .} {=word h}] {=compound {=word x} {=punct .} {=word h}} []`:`equal`,
	`[{=word x} {=punct .} {=word h}] {=string config} []`:`greater`,
	`[{=word x} {=punct .} {=word h}] {=string x.h} []`:`equal`,
	`{= {=flag {=word foo}}} {=flag {=word foobar}} []`:`lprefix`,
	`{= {=flag {=word foo}}} {=token -} []`:`rprefix`,
	`{= {=flag {=}}} {=token -} []`:`equal`,
	`{= {=word foo}} {=word foo} []`:`equal`,
	`{=compound {= {=flag {=word foo}}} {=word bar}} {=flag {=word foobar}} []`:`equal`,
	`{=compound {= {=flag {=}}} {=word foobar}} {=flag {=word foobar}} []`:`equal`,
	`{=compound {=punct .} {=word test}} {=compound {=punct .} {=word test}} []`:`equal`,
	`{=compound {=punct .} {=word test}} {=string .test} []`:`equal`,
	`{=compound {=word x} {=punct .} {=word h}} {=compound {=word x} {=punct .} {=word h}} []`:`equal`,
	`{=compound {=word x} {=punct .} {=word h}} {=string config} []`:`greater`,
	`{=compound {=word x} {=punct .} {=word h}} {=string x.h} []`:`equal`,
	`{=flag {=word foobar}} {=compound {= {=flag {=word foo}}} {=word bar}} []`:`equal`,
	`{=flag {=word foobar}} {=compound {= {=flag {=}}} {=word foobar}} []`:`equal`,
	`{=glob {=meta **} {=punct .} {=word def} {=punct .} {=word am}} {=path {=word foobar} {=word config} {=glob {=meta *} {=punct .} {=word def} {=punct .} {=word am}}} []`:`greater`,
	`{=glob {=meta **} {=punct .} {=word h}} {=glob {=meta **} {=punct .} {=word h}} []`:`equal`,
	`{=glob {=meta **} {=punct .} {=word h}} {=glob {=meta *} {=punct .} {=word h}} []`:`greater`,
	`{=glob {=meta **} {=punct .} {=word h}} {=path {=glob {=word foo} {=meta ?} {=meta ?} {=meta ?}} {=compound {=word x} {=punct .} {=word h}}} []`:`greater`,
	`{=glob {=meta **} {=punct .} {=word h}} {=path {=word foo} {=glob {=meta *} {=punct .} {=word h}}} []`:`greater`,
	`{=glob {=meta **} {=punct .} {=word h}} {=path {=word foo} {=word bar} {=glob {=word v} {=meta ?} {=punct .} {=word h}}} []`:`greater`,
	`{=glob {=meta *} {=punct .} {=word h}} {=glob {=meta **} {=punct .} {=word h}} []`:`smaller`,
	`{=glob {=meta *} {=punct .} {=word h}} {=glob {=meta *} {=punct .} {=word h}} []`:`equal`,
	`{=glob {=meta *} {=punct .} {=word h}} {=glob {=word v} {=meta ?} {=punct .} {=word h}} []`:`greater`,
	`{=list {16:16 {=word foo}}} {=list {=word foo}} []`:`equal`,
	`{=list {= {=word foo}}} {=list {=word foo}} []`:`equal`,
	`{=list {=compound {= {=flag {=word foo}}} {=word bar}}} {=list {=flag {=word foobar}}} []`:`equal`,
	`{=list {=compound {= {=flag {=}}} {=word foobar}}} {=list {=flag {=word foobar}}} []`:`equal`,
	`{=list {=flag {=word foobar}}} {=list {=compound {= {=flag {=word foo}}} {=word bar}}} []`:`equal`,
	`{=list {=flag {=word foobar}}} {=list {=compound {= {=flag {=}}} {=word foobar}}} []`:`equal`,
	`{=meta **} {=glob {=word foo} {=meta ?} {=meta ?} {=meta ?}} []`:`greater`,
	`{=meta **} {=meta **} []`:`equal`,
	`{=meta **} {=meta *} []`:`greater`,
	`{=meta **} {=word foobar} []`:`greater`,
	`{=meta **} {=word foo} []`:`greater`,
	`{=meta *} {=meta **} []`:`smaller`,
	`{=meta *} {=meta *} []`:`equal`,
	`{=meta ?} {=meta *} []`:`smaller`,
	`{=path {=word foobar} {=word config} {=glob {=meta *} {=punct .} {=word def} {=punct .} {=word am}}} {=glob {=meta **} {=punct .} {=word def} {=punct .} {=word am}} []`:`smaller`,
	`{=path {=word foo} {=glob {=meta *} {=punct .} {=word h}}} {=path {=word foo} {=glob {=meta *} {=punct .} {=word h}}} []`:`equal`,
	`{=path {=word foo} {=word bar} {=glob {=meta *} {=punct .} {=word h}}} {=path {=word foo} {=word bar} {=glob {=word v} {=meta ?} {=punct .} {=word h}}} []`:`greater`,
	`{=punct .} {=compound {=word bar} {=punct .} {=word c}} []`:`smaller`,
	`{=punct .} {=punct .} []`:`equal`,
	`{=punct .} {=string .test} []`:`lprefix`,
	`{=punct .} {=word .test} []`:`lprefix`,
	`{=punct .} {=word c} []`:`smaller`,
	`{=punct .} {=word foo} []`:`smaller`,
	`{=punct .} {=word oo} []`:`smaller`,
	`{=string bar} {=meta **} []`:`smaller`,
	`{=string foo} {=string foo} []`:`equal`,
	`{=string foo} {=word f} []`:`rprefix`,
	`{=string h} {=string h} []`:`equal`,
	`{=token **} {=token **} []`:`equal`,
	`{=token **} {=word foo} []`:`greater`,
	`{=token *} {=token **} []`:`smaller`,
	`{=token -} {= {=flag {=word foo}}} []`:`lprefix`,
	`{=token -} {= {=flag {=}}} []`:`equal`,
	`{=token .} {=string .test} []`:`lprefix`,
	`{=token .} {=token .} []`:`equal`,
	`{=token .} {=word bar} []`:`smaller`,
	`{=word bar} {=glob {=meta **} {=punct .} {=word hh}} []`:`smaller`,
	`{=word conf3} {=word bar} []`:`greater`,
	`{=word conf3} {=word foo} []`:`smaller`,
	`{=word c} {=word c} []`:`equal`,
	`{=word foobar} {=meta **} []`:`smaller`,
	`{=word foobar} {=word foobar} []`:`equal`,
	`{=word foo} {=word foobar} []`:`lprefix`,
	`{=word foo} {=word foo} []`:`equal`,
	`{=word h} {=word h} []`:`equal`,
	`{=word test} {=word test} []`:`equal`,
	`{=word xv} {=word x} []`:`rprefix`,
	`{=word x} {=string config} []`:`greater`,
	`{=word x} {=string x.h} []`:`lprefix`,
	`{=word x} {=word xxx} []`:`lprefix`,
	`{=word x} {=word x} []`:`equal`,
}
func check_cmp(ctx Context, l, lv, r, rv any, syn []bool, _r *cmpres) {
	if !truly(ctx, is_test_mode{}) { return }
	
	k := rxLC.ReplaceAllString(sf("%v %v %v", ts(l), ts(r), syn), "=")
	t := rxLC.ReplaceAllString(sf("%v", *_r), "=")
	sl := rxSquareBracket.ReplaceAllString(strings.ReplaceAll(sf("%v", l)," ",""), "$1")
	sr := rxSquareBracket.ReplaceAllString(strings.ReplaceAll(sf("%v", r)," ",""), "$1")

	s_kt := sf("`%v`:`%v`,", k, t)
	for _, rx := range []*regexp.Regexp{
		regexp.MustCompile("`"+`(.+?) (.+?) (.+?)`+"`:`"+`(lprefix|smaller|equal|greater|rprefix)`+"`,"),
	}{ if sm := rx.FindStringSubmatch(s_kt); sm != nil {
		switch sm[4] {
		case "lprefix":
			if strings.HasPrefix(sr, sl) { return }
		case "smaller":
			if sl < sr || sm[1] < sm[2] { return }
		case "equal" :
			if sl == sr || sm[1] == sm[2] { return }
		case "greater":
			if sl > sr || sm[1] > sm[2] { return }
		case "rprefix":
			if strings.HasPrefix(sl, sr) { return }
		}
		if false { debug(ctx, _f("%s | %v %v", s_kt, l, r), _f("%s | %s %s", sm[1:], sl, sr)) }
	}}

	if v := checkpoints_cmp[k]; v == "" {
		debug(ctx, _f("`%v`:`%v`,", k, t), _f("%s, %v", ts(lv), lv), _f("%s, %v", ts(rv), rv), callstack{num:10}, trace{})
	} else if v != t {
		debug(ctx, _f("`%s`", k), _f("got: %s", t), _f("!= : %s", v), callstack{num:10}, trace{})
	}
}

var checkpoints_com = map[string]map[string]any{
	".": map[string]any{
		"[] [{1:2:word test} {1:6:punct .} {1:7:word paniconexit0}]": "[test.paniconexit0] [{=compound {1:2:word test} {1:6:punct .} {1:7:word paniconexit0}}]",
		"[] [{1:21:word test} {1:25:punct .} {1:26:word timeout}]": "[test.timeout] [{=compound {1:21:word test} {1:25:punct .} {1:26:word timeout}}]",
	},
	"value": map[string]any{
		"[] [{13:11:word x} {13:13:word y}]": "[xy] [{=compound {13:11:word x} {13:13:word y}}]",
	},
}
func check_com(ctx *comctx, a, elems []Value, res *[]Value) {
	var (
		f = dirs(1, bases(_position(ctx).Filename, 2))
		k = sf("%v %v", ts(a), ts(elems))
		r = sf("%v %v", *res, ts(*res))
		t = checkpoints_com[f][k]
	)
	switch v := t.(type) {
	case   string: if r == v { return }
	case []string: for _, v := range v { if r == v { return } }
	default: if false { note(pc(ctx,elems), "%s: %v, %v => %v", f, k, t, r) }
	}
	if false { debug(pc(ctx,a), `"%v %v":"%v %v",`, a, elems, *res, trace{}) }
}

var fmt_slot = regexp.MustCompile(`%\[([0-9_a-z]+)\]s`)
var checkpoints_match = map[string]any{
	`%.c foo.c++`:`false  []`,
	`%.c foo.c`:`true foo.c [foo]`,
	`%.c foo/bar.c++`:`false  []`,
	`%.c foo/bar.c`:`true foo/bar.c [foo/bar]`,
	`%.c foo/z.c`:`true foo/z.c [foo/z]`,
	`%.c x.c++`:`false  []`,
	`%.c y.c++`:`false  []`,
	`%.c++ foo.c++`:`true foo.c++ [foo]`,
	`%.c++ foo/bar.c++`:`true foo/bar.c++ [foo/bar]`,
	`%.c++ x.c++`:`true x.c++ [x]`,
	`%.c++ y.c++`:`true y.c++ [y]`,
	`. .`:`true . []`,
	`* a.h`:`true a.h [a.h]`,
	`* a`:`true a [a]`,
	`* b.h`:`true b.h [b.h]`,
	`* b`:`true b [b]`,
	`* bar.h`:`true bar.h [bar.h]`,
	`* bar`:`true bar [bar]`,
	`* config`:`true config [config]`,
	`* foo.h`:`true foo.h [foo.h]`,
	`* foo`:`true foo [foo]`,
	`* foobar`:`true foobar [foobar]`,
	`* v1.h`:`true v1.h [v1.h]`,
	`* v2.h`:`true v2.h [v2.h]`,
	`* v?.h`:`true v?.h [v?.h]`,
	`* x.h`:`true x.h [x.h]`,
	`* xv1y.h`:`true xv1y.h [xv1y.h]`,
	`* xv22y.h`:`true xv22y.h [xv22y.h]`,
	`* xv333y.h`:`true xv333y.h [xv333y.h]`,
	`* zz`:`true zz [zz]`,
	`** `:`true  []`,
	`** a/b/c/xyz`:`true a/b/c/xyz [a/b/c/xyz]`,
	`** a/b/c`:`true a/b/c [a/b/c]`,
	`**.auto .test/a/b/c.auto`:`true .test/a/b/c.auto [.test/a/b/c]`,
	`**.auto .test/a/b/c.test`:`false <nil> []`,
	`**.c foo.c`:`true foo.c [foo]`,
	`**.c foo/bar.c`:`true foo/bar.c [foo/bar]`,
	`**.c foo/oo/oo/oo/bar.c`:`true foo/oo/oo/oo/bar.c [foo/oo/oo/oo/bar]`,
	`**.c foo/z.c`:`true foo/z.c [foo/z]`,
	`**.c++ foo.c++`:`true foo.c++ [foo]`,
	`**.c++ foo/bar.c++`:`true foo/bar.c++ [foo/bar]`,
	`**.c++ x.c++`:`true x.c++ [x]`,
	`**.c++ y.c++`:`true y.c++ [y]`,
	`**.def.am **.def.am`:`true **.def.am [**]`,
	`**.def.am *.def.am`:`true *.def.am [*]`,
	`**.def.am foo/1/2/3/bar.def.am`:`true foo/1/2/3/bar.def.am [foo/1/2/3/bar]`,
	`**.def.am foobar.def.am`:`true foobar.def.am [foobar]`,
	`**.def.am foobar/config/*.def.am`:`true foobar/config/*.def.am [foobar/config/*]`,
	`**.def.am foobar/config/*.def.in`:`false <nil> []`,
	`**.def.am foobar`:`false <nil> []`,
	`**.gen a.gen`:`true a.gen [a]`,
	`**.gen b.gen`:`true b.gen [b]`,
	`**.gen foo/c.gen`:`true foo/c.gen [foo/c]`,
	`**.h **.h`:`true **.h [**]`,
	`**.h *.h`:`true *.h [*]`,
	`**.h bar.h`:`true bar.h [bar]`,
	`**.h foo.h`:`true foo.h [foo]`,
	`**.h foo/*.h`:`true foo/*.h [foo/*]`,
	`**.h foo/a/b/c/bar.h`:`true foo/a/b/c/bar.h [foo/a/b/c/bar]`,
	`**.h foo/bar/v1.h`:`true foo/bar/v1.h [foo/bar/v1]`,
	`**.h foo/bar/v2.h`:`true foo/bar/v2.h [foo/bar/v2]`,
	`**.h foo/bar/v3.hh`:`false <nil> []`,
	`**.h foo/bar/v?.h`:`true foo/bar/v?.h [foo/bar/v?]`,
	`**.h foo/bar/xyz000.txt`:`false <nil> []`,
	`**.h foo/bar/zz/x.h`:`true foo/bar/zz/x.h [foo/bar/zz/x]`,
	`**.h foo/bar/zz`:`false <nil> []`,
	`**.h foo/bar`:`false <nil> []`,
	`**.h foo/v1.h`:`true foo/v1.h [foo/v1]`,
	`**.h foo/v2.h`:`true foo/v2.h [foo/v2]`,
	`**.h foo/xv1y.h`:`true foo/xv1y.h [foo/xv1y]`,
	`**.h foo/xv22y.h`:`true foo/xv22y.h [foo/xv22y]`,
	`**.h foo/xv333y.h`:`true foo/xv333y.h [foo/xv333y]`,
	`**.h foo???/x.h`:`true foo???/x.h [foo???/x]`,
	`**.h foo???`:`false <nil> []`,
	`**.h foo`:`false <nil> []`,
	`**.h foobar.h`:`true foobar.h [foobar]`,
	`**.h foobar/config/a.def.am`:`false <nil> []`,
	`**.h foobar/config/a.def.in`:`false <nil> []`,
	`**.h foobar/config/b.def.in`:`false <nil> []`,
	`**.h foobar/config/x.h`:`true foobar/config/x.h [foobar/config/x]`,
	`**.h foobar/config`:`false <nil> []`,
	`**.h foobar/x.h`:`true foobar/x.h [foobar/x]`,
	`**.h foobar`:`false <nil> []`,
	`**.h inc/bar.h`:`true inc/bar.h [inc/bar]`,
	`**.h inc/foo.h`:`true inc/foo.h [inc/foo]`,
	`**.h inc/foo/bar/v1.h`:`true inc/foo/bar/v1.h [inc/foo/bar/v1]`,
	`**.h inc/foo/bar/v2.h`:`true inc/foo/bar/v2.h [inc/foo/bar/v2]`,
	`**.h inc/foo/bar/v3.hh`:`false <nil> []`,
	`**.h inc/foo/bar/xyz000.txt`:`false <nil> []`,
	`**.h inc/foo/bar/zz/x.h`:`true inc/foo/bar/zz/x.h [inc/foo/bar/zz/x]`,
	`**.h inc/foo/bar/zz`:`false <nil> []`,
	`**.h inc/foo/bar`:`false <nil> []`,
	`**.h inc/foo/v1.h`:`true inc/foo/v1.h [inc/foo/v1]`,
	`**.h inc/foo/v2.h`:`true inc/foo/v2.h [inc/foo/v2]`,
	`**.h inc/foo/xv1y.h`:`true inc/foo/xv1y.h [inc/foo/xv1y]`,
	`**.h inc/foo/xv22y.h`:`true inc/foo/xv22y.h [inc/foo/xv22y]`,
	`**.h inc/foo/xv333y.h`:`true inc/foo/xv333y.h [inc/foo/xv333y]`,
	`**.h inc/foo`:`false <nil> []`,
	`**.h inc/foobar/config/a.def.am`:`false <nil> []`,
	`**.h inc/foobar/config/a.def.in`:`false <nil> []`,
	`**.h inc/foobar/config/b.def.in`:`false <nil> []`,
	`**.h inc/foobar/config/x.h`:`true inc/foobar/config/x.h [inc/foobar/config/x]`,
	`**.h inc/foobar/config`:`false <nil> []`,
	`**.h inc/foobar/x.h`:`true inc/foobar/x.h [inc/foobar/x]`,
	`**.h inc/foobar`:`false <nil> []`,
	`**.o **.o`:`true **.o [**]`,
	`**.o foo.o`:`true foo.o [foo]`,
	`**y `:`false <nil> []`,
	`**y a/b/c/y/z`:`false <nil> []`,
	`**y a/b/c/y`:`true a/b/c/y [a/b/c/]`,
	`**y a/b/cy/a/b/c/y/z`:`false <nil> []`,
	`**y a/b/cy/a/b/c/y`:`true a/b/cy/a/b/c/y [a/b/cy/a/b/c/]`,
	`**y a/b/cy/a/b/c`:`false <nil> []`,
	`**y a/b/cy/a/b`:`false <nil> []`,
	`**y a/b/cy/a`:`false <nil> []`,
	`**y a/b/cy`:`true a/b/cy [a/b/c]`,
	`**y abcy`:`true abcy [abc]`,
	`**y dy`:`true dy [d]`,
	`**y z`:`false <nil> []`,
	`**z `:`false <nil> []`,
	`**z xyz`:`true xyz [xy]`,
	`*.c foo.c`:`true foo.c [foo]`,
	`*.c foo/bar.c`:`false <nil> []`,
	`*.c foo/oo/oo/oo/bar.c`:`false <nil> []`,
	`*.def.am **.def.am`:`true **.def.am [**]`,
	`*.def.am a.def.am`:`true a.def.am [a]`,
	`*.def.am a.def.in`:`false <nil> []`,
	`*.def.am b.def.in`:`false <nil> []`,
	`*.def.am foobar/config/*.def.am`:`false <nil> []`,
	`*.def.am foobar/config/*.def.in`:`false <nil> []`,
	`*.def.am x.h`:`false <nil> []`,
	`*.def.in a.def.am`:`false <nil> []`,
	`*.def.in a.def.in`:`true a.def.in [a]`,
	`*.def.in b.def.in`:`true b.def.in [b]`,
	`*.def.in x.h`:`false <nil> []`,
	`*.gen x.gen`:`true x.gen [x]`,
	`*.gen y.gen`:`true y.gen [y]`,
	`*.h *.h`:`true *.h [*]`,
	`*.h **.h`:`true **.h [**]`,
	`*.h a.def.am`:`false <nil> []`,
	`*.h a.def.in`:`false <nil> []`,
	`*.h a.h`:`true a.h [a]`,
	`*.h a`:`false <nil> []`,
	`*.h b.def.in`:`false <nil> []`,
	`*.h b.h`:`true b.h [b]`,
	`*.h b`:`false <nil> []`,
	`*.h bar.h`:`true bar.h [bar]`,
	`*.h bar`:`false <nil> []`,
	`*.h c.h`:`true c.h [c]`,
	`*.h c`:`false <nil> []`,
	`*.h config`:`false <nil> []`,
	`*.h foo.h`:`true foo.h [foo]`,
	`*.h foo/*.h`:`false <nil> []`,
	`*.h foo/bar/v?.h`:`false <nil> []`,
	`*.h foo/bar/zz/x.h`:`false <nil> []`,
	`*.h foo???/x.h`:`false <nil> []`,
	`*.h foo???`:`false <nil> []`,
	`*.h foo`:`false <nil> []`,
	`*.h foobar`:`false <nil> []`,
	`*.h v1.h`:`true v1.h [v1]`,
	`*.h v2.h`:`true v2.h [v2]`,
	`*.h v3.hh`:`false <nil> []`,
	`*.h v?.h`:`true v?.h [v?]`,
	`*.h x.h`:`true x.h [x]`,
	`*.h xv1y.h`:`true xv1y.h [xv1y]`,
	`*.h xv22y.h`:`true xv22y.h [xv22y]`,
	`*.h xv333y.h`:`true xv333y.h [xv333y]`,
	`*.h xyz000.txt`:`false <nil> []`,
	`*.h zz`:`false <nil> []`,
	`*.hh v3.hh`:`true v3.hh [v3]`,
	`*.log *.log`:`true *.log [*]`,
	`*.log foobar.log`:`true foobar.log [foobar]`,
	`*/*.h bar.h`:`false <nil> []`,
	`*/*.h foo.h`:`false <nil> []`,
	`*/*.h v1.h`:`false <nil> []`,
	`*/*.h v2.h`:`false <nil> []`,
	`*/*.h x.h`:`false <nil> []`,
	`*/*.h xv1y.h`:`false <nil> []`,
	`*/*.h xv22y.h`:`false <nil> []`,
	`*/*.h xv333y.h`:`false <nil> []`,
	`*/*/*.h bar.h`:`false <nil> []`,
	`*/*/*.h foo.h`:`false <nil> []`,
	`*data testdata`:`true testdata [test]`,
	`.test .test`:`true .test []`,
	`.test/**/**z .test/a/b/c/xyz`:`true .test/a/b/c/xyz [a/b/c xy]`,
	`.test/**y/**y .test/a/b/cy/a/b/c/y`:`true .test/a/b/cy/a/b/c/y [a/b/c a/b/c/]`,
	`.test/**y/**y/z .test/a/b/cy/a/b/c/y/z`:`true .test/a/b/cy/a/b/c/y/z [a/b/c a/b/c/]`,
	`.test/*.h .test/a.h`:`true .test/a.h [a]`,
	`.test/*.h .test/a/b.h`:`false <nil> []`,
	`.test/*.h .test/a/b/c.h`:`false <nil> []`,
	`.test/*/*.h .test/a.h`:`false <nil> []`,
	`.test/*/*.h .test/a/b.h`:`true .test/a/b.h [a b]`,
	`.test/*/*.h .test/a/b/c.h`:`false <nil> []`,
	`.test/*/*/*.h .test/a.h`:`false <nil> []`,
	`.test/*/*/*.h .test/a/b.h`:`false <nil> []`,
	`.test/*/*/*.h .test/a/b/c.h`:`true .test/a/b/c.h [a b c]`,
	`.test/*/*/*.h .test/a/b/c/d.h`:`false <nil> []`,
	`.test/*/*/*.h .test/a/b/c/d/e.h`:`false <nil> []`,
	`.test/*?y/**y .test/a/b/cy/a/b/c/y`:`true .test/a/b/cy/a/b/c/y [a/b/c a/b/c/]`,
	`.test/a/**.c .test/a/b/c.auto`:`false <nil> []`,
	`.test/a/**.c .test/a/b/c.none`:`false <nil> []`,
	`.test/x**/**y .test/xa/b/c/dy`:`true .test/xa/b/c/dy [a/b/c d]`,
	`.test/x**/**y .test/xabc/abcy`:`true .test/xabc/abcy [abc abc]`,
	`.test/x**y .test/x/xx-yy/y`:`true .test/x/xx-yy/y [/xx-yy/]`,
	`.test/x**y .test/xxx-yyx/y`:`true .test/xxx-yyx/y [xx-yyx/]`,
	`.test/x**y .test/xxx-yyx/z`:`false <nil> []`,
	`.test/x**y .test/xxx-yyx`:`false <nil> []`,
	`.test/x**y .test/xxx-yyy`:`true .test/xxx-yyy [xx-yy]`,
	`.test/x**y .test/xxx/a/b/c/yyy`:`true .test/xxx/a/b/c/yyy [xx/a/b/c/yy]`,
	`.test/x**y/x** .test/xaaa/bbb/ccc/y/xxx/xx`:`true .test/xaaa/bbb/ccc/y/xxx/xx [aaa/bbb/ccc/ xx/xx]`,
	`.test/x**y/x** .test/xaabbccy/xabc`:`true .test/xaabbccy/xabc [aabbcc abc]`,
	`.test/x**y/x**y .test/xaa/bb/ccy/xaa/bb/ccy`:`true .test/xaa/bb/ccy/xaa/bb/ccy [aa/bb/cc aa/bb/cc]`,
	`.test/x**y/x**y .test/xaaay/x/aaa/y`:`true .test/xaaay/x/aaa/y [aaa /aaa/]`,
	`.test/x**y/z .test/xxx-yyy/z`:`true .test/xxx-yyy/z [xx-yy]`,
	`.test/x**y/z .test/xxx/a/b/c/yyy/z`:`true .test/xxx/a/b/c/yyy/z [xx/a/b/c/yy]`,
	`.test/x*?/**y .test/xa/b/c/dy`:`true .test/xa/b/c/dy [a b/c/d]`,
	`.test/x*?/**y .test/xabc/abcy`:`true .test/xabc/abcy [abc abc]`,
	`.test/x*?y .test/x/xx-yy/y`:`false <nil> []`,
	`.test/x*?y/x*?y .test/xaa/bb/ccy/xaa/bb/ccy`:`true .test/xaa/bb/ccy/xaa/bb/ccy [aa/bb/cc aa/bb/cc]`,
	`.test/x*?y/x*?y .test/xaaay/x/aaa/y`:`true .test/xaaay/x/aaa/y [aaa /aaa/]`,
	`/builtins /builtins/trimprefix`:`false <nil> []`,
	`?.h x.h`:`true x.h [x]`,
	`^\.test\.([0-9]+)$ .test.10`:`true .test.10 [10]`,
	`^\.test\.([0-9]+)$ .test.11`:`true .test.11 [11]`,
	`^\.test\.([0-9]+)$ .test.12`:`true .test.12 [12]`,
	`^\.test\.([0-9]+)$ .test.13`:`true .test.13 [13]`,
	`^\.test\.([0-9]+)$ .test.1`:`true .test.1 [1]`,
	`^\.test\.([0-9]+)$ .test.2`:`true .test.2 [2]`,
	`^\.test\.([0-9]+)$ .test.3`:`true .test.3 [3]`,
	`^\.test\.([0-9]+)$ .test.4`:`true .test.4 [4]`,
	`^\.test\.([0-9]+)$ .test.5`:`true .test.5 [5]`,
	`^\.test\.([0-9]+)$ .test.6`:`true .test.6 [6]`,
	`^\.test\.([0-9]+)$ .test.7`:`true .test.7 [7]`,
	`^\.test\.([0-9]+)$ .test.8`:`true .test.8 [8]`,
	`^\.test\.([0-9]+)$ .test.9`:`true .test.9 [9]`,
	`^configure\.types\.(<(.+?)>|"(.+?)") .self`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") .usee`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") 1`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond01`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond02`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond03`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond0`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond11`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond12`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond13`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") cond1`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") configure.types."atomic.h"`:`true configure.types."atomic.h" ["atomic.h"  atomic.h]`,
	`^configure\.types\.(<(.+?)>|"(.+?)") configure.types.<atomic.h>`:`true configure.types.<atomic.h> [<atomic.h> atomic.h ]`,
	`^configure\.types\.(<(.+?)>|"(.+?)") disjunction00`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") disjunction01`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") disjunction02`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") disjunction03`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") disjunction0`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") disjunction1`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") disjunction2`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") glob1`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") glob2`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") glob3`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") modifiers`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") regex1`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") regex2`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") regex3`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") regex4`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") regex5`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") regex6`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val10`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val1`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val2`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val3`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val4`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val5`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val6`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val7`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val8`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") val9`:`false <nil> []`,
	`^configure\.types\.(<(.+?)>|"(.+?)") vals`:`false <nil> []`,
	`^val([1-9])$ .self`:`false <nil> []`,
	`^val([1-9])$ .usee`:`false <nil> []`,
	`^val([1-9])$ 1`:`false <nil> []`,
	`^val([1-9])$ 2`:`false <nil> []`,
	`^val([1-9])$ 3`:`false <nil> []`,
	`^val([1-9])$ 4`:`false <nil> []`,
	`^val([1-9])$ 5`:`false <nil> []`,
	`^val([1-9])$ 6`:`false <nil> []`,
	`^val([1-9])$ 7`:`false <nil> []`,
	`^val([1-9])$ 8`:`false <nil> []`,
	`^val([1-9])$ 9`:`false <nil> []`,
	`^val([1-9])$ _`:`false <nil> []`,
	`^val([1-9])$ a`:`false <nil> []`,
	`^val([1-9])$ foo0`:`false <nil> []`,
	`^val([1-9])$ foo1`:`false <nil> []`,
	`^val([1-9])$ val01`:`false <nil> []`,
	`^val([1-9])$ val02`:`false <nil> []`,
	`^val([1-9])$ val03`:`false <nil> []`,
	`^val([1-9])$ val04`:`false <nil> []`,
	`^val([1-9])$ val0`:`false <nil> []`,
	`^val([1-9])$ val1`:`true val1 [1]`,
	`^val([1-9])$ val2`:`true val2 [2]`,
	`^val([1-9])$ val3`:`true val3 [3]`,
	`^val([1-9])$ val4`:`true val4 [4]`,
	`^val([1-9])$ val5`:`true val5 [5]`,
	`^var\.([xy]+) var.xxx`:`true var.xxx [xxx]`,
	`^var\.([xy]+) var.yyy`:`true var.yyy [yyy]`,
	`^var\.([xyz]+) var.xxx`:`true var.xxx [xxx]`,
	`^var\.([xyz]+) var.yyy`:`true var.yyy [yyy]`,
	`^var\.([xyz]+) var.zzz`:`true var.zzz [zzz]`,
	`auto auto`:`true auto []`,
	`auto test`:`false <nil> []`,
	`b* b?r`:`true b?r [?r]`,
	`b* bar`:`true bar [ar]`,
	`b?r b*`:`false <nil> [*]`,
	`b?r bar`:`true bar [a]`,
	`b?r/v?.h v1.h`:`false <nil> []`,
	`b?r/v?.h v2.h`:`false <nil> []`,
	`b?r/v?.h xv1y.h`:`false <nil> []`,
	`b?r/v?.h xv22y.h`:`false <nil> []`,
	`b?r/v?.h xv333y.h`:`false <nil> []`,
	`bar *.h`:`false <nil> []`,
	`bar bar`:`true bar []`,
	`bar v1.h`:`false <nil> []`,
	`bar v2.h`:`false <nil> []`,
	`bar xv1y.h`:`false <nil> []`,
	`bar xv22y.h`:`false <nil> []`,
	`bar xv333y.h`:`false <nil> []`,
	`bar/*.hh v1.h`:`false <nil> []`,
	`bar/*.hh v2.h`:`false <nil> []`,
	`bar/*.hh xv1y.h`:`false <nil> []`,
	`bar/*.hh xv22y.h`:`false <nil> []`,
	`bar/*.hh xv333y.h`:`false <nil> []`,
	`bar/v?.h v1.h`:`false <nil> []`,
	`bar/v?.h v2.h`:`false <nil> []`,
	`bar/v?.h xv1y.h`:`false <nil> []`,
	`bar/v?.h xv22y.h`:`false <nil> []`,
	`bar/v?.h xv333y.h`:`false <nil> []`,
	`builtins builtins/trimprefix`:`false builtins []`,
	`c c`:`true c []`,
	`config config`:`true config []`,
	`config x.h`:`false <nil> []`,
	`config/*.def.am x.h`:`false <nil> []`,
	`config/*.def.in x.h`:`false <nil> []`,
	`f*?/x.h fo?/**/x.h`:`true fo?/**/x.h [o?/**/x.h]`,
	`f*?/x.h foo/**/x.h`:`true foo/**/x.h [oo/**/x.h]`,
	`f*?/x.h foo/b?r/v?.h`:`false <nil> []`,
	`fo? foo`:`true foo [o]`,
	`fo?/**/x.h f*?/x.h`:`true <nil> []`,
	`fo?/**/x.h foo/b*/v*.h`:`false foo/b*/v*.h [o b*/v*.h]`,
	`fo?/**/x.h foo/x*y.h`:`false <nil> []`,
	`foo **.h`:`false <nil> []`,
	`foo *.h`:`false <nil> []`,
	`foo bar.h`:`false <nil> []`,
	`foo foo.h`:`false foo []`,
	`foo foo.o`:`false foo []`,
	`foo foo.txt`:`false foo []`,
	`foo foo???`:`false foo []`,
	`foo foo`:`true foo []`,
	`foo foobar`:`false foo []`,
	`foo/**.hh **.h`:`false <nil> []`,
	`foo/**.hh *.h`:`false <nil> []`,
	`foo/**.hh foo/*.h`:`false <nil> []`,
	`foo/**.hh foo/bar/*.hh`:`true foo/bar/*.hh [bar/*]`,
	`foo/**/x.h f*?/x.h`:`true <nil> []`,
	`foo/**/x.h foo/b*/v*.h`:`false <nil> []`,
	`foo/**/x.h foo/x*y.h`:`false <nil> []`,
	`foo/*.h **.h`:`true <nil> []`,
	`foo/*.h *.h`:`false <nil> []`,
	`foo/*.h foo/**.hh`:`false <nil> []`,
	`foo/*.h foo/*.h`:`true foo/*.h [*]`,
	`foo/*.h foo/bar/*.h`:`false <nil> []`,
	`foo/*.h foo/bar/*/*.h`:`false <nil> []`,
	`foo/*.h foo/bar/v1.h`:`false <nil> []`,
	`foo/*.h foo/bar/v2.h`:`false <nil> []`,
	`foo/*.h foo/bar/v?.h`:`false <nil> []`,
	`foo/*.h foo/bar/z?/?.h`:`false <nil> []`,
	`foo/*.h foo/bar/zz/?.h`:`false <nil> []`,
	`foo/*.h foo/bar/zz/x.h`:`false <nil> []`,
	`foo/*.h foo???/x.h`:`false <nil> []`,
	`foo/*.hh *.h`:`false <nil> []`,
	`foo/b*/v*.h fo?/**/x.h`:`false <nil> []`,
	`foo/b*/v*.h foo/**/x.h`:`false <nil> []`,
	`foo/b*/v*.h foo/b?r/v?.h`:`true foo/b?r/v?.h [?r ?]`,
	`foo/b*/v*.h foo/bar/v1.h`:`true foo/bar/v1.h [ar 1]`,
	`foo/b*/v*.h foo/bar/v2.h`:`true foo/bar/v2.h [ar 2]`,
	`foo/b?r/v?.h f*?/x.h`:`false <nil> []`,
	`foo/b?r/v?.h foo/b*/v*.h`:`false <nil> []`,
	`foo/bar/*.h foo/**.hh`:`false <nil> []`,
	`foo/bar/*.h foo/*.h`:`false <nil> []`,
	`foo/bar/*.h foo/bar/v?.h`:`true foo/bar/v?.h [v?]`,
	`foo/bar/*.h foo/bar/zz/x.h`:`false <nil> []`,
	`foo/bar/*.h foo???/x.h`:`false <nil> []`,
	`foo/bar/*.hh foo/**.hh`:`false <nil> []`,
	`foo/bar/*/*.h foo/**.hh`:`false <nil> []`,
	`foo/bar/*/*.h foo/*.h`:`false <nil> []`,
	`foo/bar/*/*.h foo/bar/v?.h`:`false foo/bar/v?.h [v?.h]`,
	`foo/bar/*/*.h foo/bar/zz/x.h`:`true foo/bar/zz/x.h [zz x]`,
	`foo/bar/*/*.h foo???/x.h`:`false <nil> []`,
	`foo/bar/v?.h **.h`:`true <nil> []`, // or `true foo/bar/v?.h [foo/bar/v?]` ?
	`foo/bar/v?.h *.h`:`false <nil> []`,
	`foo/bar/v?.h foo/*.h`:`false <nil> []`,
	`foo/bar/v?.h foo/bar/*.h`:`false <nil> []`,
	`foo/bar/v?.h foo/bar/*/*.h`:`false <nil> []`,
	`foo/bar/v?.h foo/bar/v1.h`:`true foo/bar/v1.h [1]`,
	`foo/bar/v?.h foo/bar/v2.h`:`true foo/bar/v2.h [2]`,
	`foo/bar/v?.h foo/bar/z?/?.h`:`false <nil> []`,
	`foo/bar/z?/?.h foo/*.h`:`false <nil> []`,
	`foo/bar/z?/?.h foo/bar/zz/x.h`:`true foo/bar/zz/x.h [z x]`,
	`foo/bar/z?/?.h foo???/x.h`:`false <nil> []`,
	`foo/bar/zz/?.h foo/*.h`:`false <nil> []`,
	`foo/bar/zz/?.h foo/bar/zz/x.h`:`true foo/bar/zz/x.h [x]`,
	`foo/bar/zz/?.h foo???/x.h`:`false <nil> []`,
	`foo/bar/zz/x.h *.h`:`false <nil> []`,
	`foo/bar/zz/x.h **.h`:`true <nil> []`,
	`foo/bar/zz/x.h foo/bar/z?/?.h`:`false <nil> []`,
	`foo/x*y.h foo/xv*y.h`:`true foo/xv*y.h [v*]`,
	`foo/x*y.h foo/xv1y.h`:`true foo/xv1y.h [v1]`,
	`foo/xv*y.h foo/b*/v*.h`:`false <nil> []`,
	`foo/xv*y.h foo/x*y.h`:`false <nil> []`,
	`foo/z.c foo.o`:`false <nil> []`,
	`foo/z.c foo/bar.o`:`false <nil> []`,
	`foo/z.c foo/z.o`:`false <nil> []`,
	`foo/z.c x.o`:`false <nil> []`,
	`foo/z.c y.o`:`false <nil> []`,
	`foo/z.gen **.gen`:`true foo/z [foo z]`,
	`foo/z.gen *.gen`:`false <nil> []`,
	`foo??? **.h`:`false <nil> []`,
	`foo??? *.h`:`false <nil> []`,
	`foo??? bar.h`:`false <nil> []`,
	`foo??? foo.h`:`false <nil> []`,
	`foo??? foo`:`false <nil> []`,
	`foo??? foobar`:`true foobar [b a r]`,
	`foo???/x.h **.h`:`true <nil> []`,
	`foo???/x.h *.h`:`false <nil> []`,
	`foo???/x.h foo/*.h`:`false <nil> []`,
	`foo???/x.h foo/bar/*.h`:`false <nil> []`,
	`foo???/x.h foo/bar/*/*.h`:`false <nil> []`,
	`foo???/x.h foo/bar/z?/?.h`:`false <nil> []`,
	`foo???/x.h foo/bar/zz/?.h`:`false <nil> []`,
	`foobar **.def.am`:`false <nil> []`,
	`foobar *.def.am`:`false <nil> []`,
	`foobar bar.h`:`false <nil> []`,
	`foobar foo.h`:`false <nil> []`,
	`foobar foo`:`false <nil> []`,
	`foobar foobar`:`true foobar []`,
	`foobar/config/*.def.am **.def.am`:`true <nil> []`,
	`foobar/config/*.def.am **.h`:`false <nil> []`,
	`foobar/config/*.def.am *.def.am`:`false <nil> []`,
	`foobar/config/*.def.am foo/bar/zz/x.h`:`false <nil> []`,
	`foobar/config/*.def.in **.def.am`:`false <nil> []`,
	`foobar/config/*.def.in **.h`:`false <nil> []`,
	`foobar/config/*.def.in *.def.am`:`false <nil> []`,
	`foobar/config/*.def.in foo/bar/zz/x.h`:`false <nil> []`,
	`fo{2}(/o{2}){3}/bar\.c foo/oo/oo/oo/bar.c`:`true foo/oo/oo/oo/bar.c [/oo]`,
	`fo{2}/bar\.c foo/bar.c`:`true foo/bar.c []`,
	`fo{2}\.c foo.c`:`true foo.c []`,
	`inc .DS_Store`:`false <nil> []`,
	`inc 1`:`false <nil> []`,
	`inc 2`:`false <nil> []`,
	`inc 3`:`false <nil> []`,
	`inc 4`:`false <nil> []`,
	`inc do.smart`:`false <nil> []`,
	`inc inc`:`true inc []`,
	`t*a testdata`:`true testdata [estdat]`,
	`test test`:`true test []`,
	`test* testdata`:`true testdata [data]`,
	`v*.h v1.h`:`true v1.h [1]`,
	`v*.h v2.h`:`true v2.h [2]`,
	`v*.h v?.h`:`true v?.h [?]`,
	`v?.h v1.h`:`true v1.h [1]`,
	`v?.h v2.h`:`true v2.h [2]`,
	`v?.h v3.hh`:`false <nil> []`,
	`v?.h xyz000.txt`:`false <nil> []`,
	`v?.h zz`:`false <nil> []`,
	`x x.h`:`false x []`,
	`x x.o`:`false x []`,
	`x** xa/b/c/dy`:`true xa/b/c/dy [a/b/c/dy]`,
	`x** xa/b/c`:`true xa/b/c [a/b/c]`,
	`x** xabc/abcy`:`true xabc/abcy [abc/abcy]`,
	`x** xabc`:`true xabc [abc]`,
	`x** xxx/xx`:`true xxx/xx [xx/xx]`,
	`x**y `:`false <nil> []`,
	`x**y x/aaa/y`:`true x/aaa/y [/aaa/]`,
	`x**y x/xx-yy/y`:`true x/xx-yy/y [/xx-yy/]`,
	`x**y xaa/bb/ccy/xaa/bb/ccy`:`true xaa/bb/ccy/xaa/bb/ccy [aa/bb/ccy/xaa/bb/cc]`,
	`x**y xaa/bb/ccy/xaa/bb`:`false <nil> []`,
	`x**y xaa/bb/ccy/xaa`:`false <nil> []`,
	`x**y xaa/bb/ccy`:`true xaa/bb/ccy [aa/bb/cc]`,
	`x**y xaaa/bbb/ccc/y/xxx/xx`:`false <nil> []`,
	`x**y xaaa/bbb/ccc/y/xxx`:`false <nil> []`,
	`x**y xaaa/bbb/ccc/y`:`true xaaa/bbb/ccc/y [aaa/bbb/ccc/]`,
	`x**y xaaay/x/aaa/y`:`true xaaay/x/aaa/y [aaay/x/aaa/]`,
	`x**y xaaay/x/aaa`:`false <nil> []`,
	`x**y xaaay/x`:`false <nil> []`,
	`x**y xaaay`:`true xaaay [aaa]`,
	`x**y xaabbccy/xabc`:`false <nil> []`,
	`x**y xaabbccy`:`true xaabbccy [aabbcc]`,
	`x**y xxx-yyx/y`:`true xxx-yyx/y [xx-yyx/]`,
	`x**y xxx-yyx/z`:`false <nil> []`,
	`x**y xxx-yyx`:`false <nil> []`,
	`x**y xxx-yyy/z`:`false <nil> []`,
	`x**y xxx-yyy`:`true xxx-yyy [xx-yy]`,
	`x**y xxx/a/b/c/yyy/z`:`false <nil> []`,
	`x**y xxx/a/b/c/yyy`:`true xxx/a/b/c/yyy [xx/a/b/c/yy]`,
	`x*y.h xv*y.h`:`true xv*y.h [v*]`,
	`x*y.h xv1y.h`:`true xv1y.h [v1]`,
	`x.c++ x.o`:`false x. []`,
	`x.h config`:`false <nil> []`,
	`x.h x.h`:`true x.h []`,
	`xv*y.h xv1y.h`:`true xv1y.h [1]`,
	`xv*y.h xv22y.h`:`true xv22y.h [22]`,
	`xv*y.h xv333y.h`:`true xv333y.h [333]`,
	`y y.o`:`false y []`,
	`y.c++ y.o`:`false y. []`,
	`z z.o`:`false z []`,
	`z z`:`true z []`,
	`z.c z.o`:`false z. []`,
	`z? zz`:`true zz [z]`,
	testdata_f(`%[1]s builtins/trimprefix`                  ):`false <nil> []`,
	testdata_f(`%%%%/testdata %[1]s/builtins/trimprefix`    ):testdata_f(`false [%[2]s] [%[1]s]`,trim_suffix{1,"/testdata"}),
	testdata_f(`%%%%/testdata/ %[1]s/builtins/trimprefix`   ):testdata_f(`false [%[2]s ] [%[1]s]`,trim_suffix{1,"/testdata"}),
	testdata_f(`**/testdata %[1]s/builtins/trimprefix`      ):testdata_f(`false [%[2]s] [%[1]s]`,trim_suffix{1,"/testdata"}),
	testdata_f(`**/testdata/ %[1]s/builtins/trimprefix`     ):testdata_f(`false [%[2]s ] [%[1]s]`,trim_suffix{1,"/testdata"}),
	testdata_f(`**/testdata/** %[1]s/builtins/trimprefix`   ):testdata_f(`true [%[2]s builtins trimprefix] [%[1]s builtins/trimprefix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`**/testdata/** %[1]s/builtins/trimsuffix`   ):testdata_f(`true [%[2]s builtins trimsuffix] [%[1]s builtins/trimsuffix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`**/testdata/**/ %[1]s/builtins/trimprefix/` ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s builtins/trimprefix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`**/testdata/**/ %[1]s/builtins/trimsuffix/` ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s builtins/trimsuffix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`*?/testdata %[1]s/builtins/trimprefix`      ):testdata_f(`false [%[2]s] [%[1]s]`,trim_suffix{1,"/testdata"}),
	testdata_f(`*?/testdata %[1]s`                          ):testdata_f(`true [%[2]s] [%[1]s]`,trim_suffix{1,"/testdata"}),
	testdata_f(`*?/testdata/ %[1]s/`                        ):testdata_f(`true [%[2]s ] [%[1]s]`,trim_suffix{1,"testdata"}),
	testdata_f(`*?/testdata/ %[1]s/builtins/trimprefix`     ):testdata_f(`false [%[2]s ] [%[1]s]`,trim_suffix{1,"/testdata"}),
	testdata_f(`*?/testdata/*? %[1]s/builtins/trimprefix`   ):testdata_f(`true [%[2]s builtins trimprefix] [%[1]s builtins/trimprefix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`*?/testdata/*?/ %[1]s/builtins/trimprefix/` ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s builtins/trimprefix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`*?/testdata/*? %[1]s/builtins/trimsuffix`   ):testdata_f(`true [%[2]s builtins trimsuffix] [%[1]s builtins/trimsuffix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`*?/testdata/*?/ %[1]s/builtins/trimsuffix/` ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s builtins/trimsuffix]`,trim_suffix{1,"/testdata"}),
	testdata_f(`/%%%%/testdata %[1]s/builtins/trimprefix`   ):testdata_f(`false [%[2]s] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/%%%%/testdata/ %[1]s/builtins/trimprefix`  ):testdata_f(`false [%[2]s ] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/ %[1]s/builtins/trimprefix/`            ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s/builtins/trimprefix]`,trim_prefix{1,"/"}),
	testdata_f(`/**/ %[1]s/builtins/trimsuffix/`            ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s/builtins/trimsuffix]`,trim_prefix{1,"/"}),
	testdata_f(`/**/ %[1]s/builtins/trimprefix`             ):testdata_f(`false [%[2]s builtins ] [%[1]s/builtins/]`,trim_prefix{1,"/"}),
	testdata_f(`/**/ %[1]s/builtins/trimsuffix`             ):testdata_f(`false [%[2]s builtins ] [%[1]s/builtins/]`,trim_prefix{1,"/"}),
	testdata_f(`/*?/ %[1]s/builtins/trimprefix/`            ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s/builtins/trimprefix]`,trim_prefix{1,"/"}),
	testdata_f(`/*?/ %[1]s/builtins/trimsuffix/`            ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s/builtins/trimsuffix]`,trim_prefix{1,"/"}),
	testdata_f(`/*?/ %[1]s/builtins/trimprefix`             ):testdata_f(`false [%[2]s builtins ] [%[1]s/builtins/]`,trim_prefix{1,"/"}),
	testdata_f(`/*?/ %[1]s/builtins/trimsuffix`             ):testdata_f(`false [%[2]s builtins ] [%[1]s/builtins/]`,trim_prefix{1,"/"}),
	testdata_f(`/**/testdata %[1]s/builtins/trimprefix`     ):testdata_f(`false [%[2]s] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/testdata/ %[1]s/builtins/trimprefix`    ):testdata_f(`false [%[2]s ] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/testdata/** %[1]s/builtins/trimprefix`  ):testdata_f(`true [%[2]s builtins trimprefix] [%[1]s builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/testdata/** %[1]s/builtins/trimsuffix`  ):testdata_f(`true [%[2]s builtins trimsuffix] [%[1]s builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/testdata/**/ %[1]s/builtins/trimprefix/`):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/testdata/**/ %[1]s/builtins/trimsuffix/`):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata %[1]s/builtins/trimprefix`     ):testdata_f(`false [%[2]s] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata %[1]s`                         ):testdata_f(`true [%[2]s] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata/ %[1]s/`                       ):testdata_f(`true [%[2]s ] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata/ %[1]s/builtins/trimprefix`    ):testdata_f(`false [%[2]s ] [%[1]s]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata/*? %[1]s/builtins/trimprefix`  ):testdata_f(`true [%[2]s builtins trimprefix] [%[1]s builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata/*? %[1]s/builtins/trimsuffix`  ):testdata_f(`true [%[2]s builtins trimsuffix] [%[1]s builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata/*?/ %[1]s/builtins/trimprefix/`):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/testdata/*?/ %[1]s/builtins/trimsuffix/`):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/test*/*?/ %[1]s/builtins/trimprefix/`   ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s data builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/test*/**/ %[1]s/builtins/trimprefix/`   ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s data builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/test*/*?/ %[1]s/builtins/trimsuffix/`   ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s data builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/test*/**/ %[1]s/builtins/trimsuffix/`   ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s data builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/*data/*?/ %[1]s/builtins/trimprefix/`   ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s test builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/*data/*?/ %[1]s/builtins/trimprefix/`   ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s test builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/*data/*?/ %[1]s/builtins/trimsuffix/`   ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s test builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/**/*data/*?/ %[1]s/builtins/trimsuffix/`   ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s test builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/t*a/*?/ %[1]s/builtins/trimprefix/`     ):testdata_f(`true [%[2]s builtins trimprefix ] [%[1]s estdat builtins/trimprefix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/*?/t*a/*?/ %[1]s/builtins/trimsuffix/`     ):testdata_f(`true [%[2]s builtins trimsuffix ] [%[1]s estdat builtins/trimsuffix]`,trim_prefix{1,"/"},trim_suffix{1,"/testdata"}),
	testdata_f(`/builtins %[1]s/builtins/trimprefix`        ):`false <nil> []`,
	testdata_f(`/testdata/%%%% %[1]s/builtins/trimsuffix`   ):`false [ testdata builtins trimsuffix] [builtins/trimsuffix]`,
	testdata_f(`/testdata/%%%% %[1]s/builtins/trimsuffix/`  ):`false [ testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`/testdata/%%%%/ %[1]s/builtins/trimsuffix/` ):`false [ testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`/testdata/** %[1]s/builtins/trimsuffix`     ):`false [ testdata builtins trimsuffix] [builtins/trimsuffix]`,
	testdata_f(`/testdata/** %[1]s/builtins/trimsuffix/`    ):`false [ testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`/testdata/**/ %[1]s/builtins/trimsuffix`    ):`false <nil> []`,
	testdata_f(`/testdata/**/ %[1]s/builtins/trimsuffix/`   ):`false [ testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`testdata/** %[1]s/builtins/trimsuffix`      ):`false [testdata builtins trimsuffix] [builtins/trimsuffix]`,
	testdata_f(`testdata/** %[1]s/builtins/trimsuffix/`     ):`false [testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`testdata/**/ %[1]s/builtins/trimsuffix`     ):`false <nil> []`,
	testdata_f(`testdata/**/ %[1]s/builtins/trimsuffix/`    ):`false [testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`testdata/%%%% %[1]s/builtins/trimsuffix`    ):`false [testdata builtins trimsuffix] [builtins/trimsuffix]`,
	testdata_f(`testdata/%%%% %[1]s/builtins/trimsuffix/`   ):`false [testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`testdata/%%%%/ %[1]s/builtins/trimsuffix`   ):`false <nil> []`,
	testdata_f(`testdata/%%%%/ %[1]s/builtins/trimsuffix/`  ):`false [testdata builtins trimsuffix ] [builtins/trimsuffix]`,
	testdata_f(`testdata/builtins/trimsuffix %[1]s/builtins/trimsuffix`):`false [testdata builtins trimsuffix] []`,
	testdata_f(`builtins/trimsuffix %[1]s`,trim_suffix{1,"testdata"}):`false <nil> []`,
}
func check_match(ctx Context, pat, val any, _full *bool, _res *Value, _stems *[]Value) {
	var k = rxLC.ReplaceAllString(sf("%v %v", __string(ctx,pat), __string(ctx,val)), "=")
	var t = rxLC.ReplaceAllString(sf("%v %v %v", *_full, *_res, *_stems), "=")

	if fmt_slot.MatchString(k) { k = sf(k, testdata_s, strings.Split(testdata_s, pathSep)) }

	var s_kt = sf("`%v`:`%v`,", k, t)
	for _, rx := range []*regexp.Regexp{
		regexp.MustCompile("`"+`(.+?) (.+?)`+"`:`"+`(false|true) (.+?) (.+?)`+"`,"),
	}{ if sm := rx.FindStringSubmatch(s_kt); sm != nil {
		switch sm[3] {
		case "true" :
			if /* sm[1] == sm[2] && */ sm[2] == sm[4] { return }
			if sm[4] == "<nil>" && sm[5] == "[]" && isPattern(ctx, sm[2]) { return }
		case "false":
			if sm[1] != sm[2] {
				if sm[4] == "<nil>" && sm[5] == "[]" { return }
				if strings.HasPrefix(sm[2], sm[4]) { return }
			}
		}
		if true { debug(ctx, _f("%s", s_kt), _f("%s", sm[1:])) }
	}}
	
	if v := checkpoints_match[k]; v == nil {
		debug(ctx, _f("`%v`:`%v`,", k, t), _f("pat: %v", ts(pat)), _f("val: %v", ts(val)),
			callstack{num:10}, trace{})
	} else if v != t {
		debug(ctx, _f(`%s | match(%s, %s)`, k, ts(pat), ts(val)), _f("got: %s", t), _f("!= : %s", v),
			callstack{num:10}, trace{})
	}
}

var checkpoints__string_com = map[string]any{
	`$1$2$3`:`{}{}{}`,
	`&(.test.$_)⌜foo bar⌟{}99`:`{}⌜foo bar⌟{}99`,
	`&(.test.bar)⌜foo bar⌟{}88`:`{}⌜foo bar⌟{}88`,
	`&(.test.bar)⌜foo bar⌟{}99`:`{}⌜foo bar⌟{}99`,
	`&(.test.foo)⌜foo bar⌟{}88`:`{}⌜foo bar⌟{}88`,
	`&(.test.foo)⌜foo bar⌟{}99`:`{}⌜foo bar⌟{}99`,
	`&(.test.h)a`:`-a`, `&(.test.h)b`:`-b`, `&(.test.h)c`:`-c`,
	`&(target.arch)-&(target.vendor)-&(target.os)-&(target.abi)`:`foo-bar-{}-0`,
	`*.h`:`*.h`,
	`*.def.am`:`*.def.am`,
	`**.h`:`**.h`,
	`**.def.am`:`**.def.am`,
	`,`:`,`,
	`-a`:`-a`, `-b`:`-b`, `-c`:`-c`,
	`-foobar`:`-foobar`,
	`.`:`.`,
	`.c++`:`.c++`,
	`.c`:`.c`,
	`.deps`:`.deps`,
	`.hh`:`.hh`,
	`.test.v`:`.test.v`,
	`.test`:`.test`,
	`.test~&(.test.s)`:`.test~foo`,
	`.tmp`:`.tmp`,
	`1x`:`1x`, `2x`:`2x`, `3x`:`3x`,
	`D.c`:`D.c`, `D.c++`:`D.c++`,
	`I.c`:`I.c`, `I.c++`:`I.c++`,
	`V{}{}`:`V{}{}`,
	`Xxa`:`Xxa`, `Xxb`:`Xxb`,
	`X{&(.test.xa)}`:`X~1~`,
	`X{&(.test.xb)}`:`X~2~`,
	`X~1~`:`X~1~`, `X~2~`:`X~2~`,
	`YX{&(.test.xa)}`:`YX~1~`,
	`YX{&(.test.xb)}`:`YX~2~`,
	`YX~1~`:`YX~1~`, `YX~2~`:`YX~2~`,
	`a-b-3-abc`:`a-b-3-abc`,
	`a-b-3`:`a-b-3`,
	`a-b`:`a-b`,
	`a.gen`:`a.gen`, `b.gen`:`b.gen`, `c.gen`:`c.gen`,
	`a.h`:`a.h`, // {=compound {31:18:word a} {31:19:punct .} {31:20:word h}}
	`a\,b\,c,x\,y\,z`:`a\,b\,c,x\,y\,z`,
	`a\,b\,c`:`a\,b\,c`,
	`aa-bb`:`aa-bb`, `ab-ba`:`ab-ba`,
	`aa`:`aa`, `ab`:`ab`,
	`abc`:`abc`, `acc`:`acc`,
	`aox.o.a`:`aox.o.a`, `aox.o.b`:`aox.o.b`, `aox.o.c`:`aox.o.c`,
	`atomic.h,`:`atomic.h,`, // {=compound {52:29 {51:24:raw atomic.h}} {52:30:punct ,}}
	`atomic.h.`:`atomic.h.`, // {=compound {52:33 {51:24:raw atomic.h}} {52:34:punct .}}
	`ax`:`ax`,
	`axx{}`:`axx{}`, `ayy{}`:`ayy{}`,
	`a{}`:`a{}`,
	`a~`:`a~`,
	`b-3`:`b-3`,
	`b-a`:`b-a`,
	`b.h`:`b.h`,
	`ba-ab`:`ba-ab`,
	`ba`:`ba`,
	`bar,`:`bar,`,
	`bar.c++`:`bar.c++`,
	`bar.c`:`bar.c`,
	`bara`:`bara`, `barb`:`barb`, `barc`:`barc`,
	`baxx{}`:`baxx{}`,
	`bayy{}`:`bayy{}`,
	`bb-aa`:`bb-aa`,
	`bb`:`bb`,
	`bcc`:`bcc`,
	`box.o.a`:`box.o.a`,
	`box.o.b`:`box.o.b`,
	`box.o.c`:`box.o.c`,
	`bx`:`bx`,
	`bx{}`:`bx{}`,
	`by{}`:`by{}`,
	`bz{}`:`bz{}`,
	`b{}`:`b{}`,
	`b~`:`b~`,
	`c.D`:`c.D`, `c++.D`:`c++.D`, `c.I`:`c.I`, `c++.I`:`c++.I`,
	`c.auto`:`c.auto`, `c.test`:`c.test`,
	`c.h`:`c.h`, `d.h`:`d.h`, `e.h`:`e.h`,
	`c.none`:`c.none`,
	`conf3,`:`conf3,`,
	`do.smart`:`do.smart`,
	`dst-nomap`:`dst-nomap`,
	`err-dst-nomap`:`err-dst-nomap`,
	`f*?`:`f*?`,
	`fo-a1`:`fo-a1`, `fo-b2`:`fo-b2`, `fo-c3`:`fo-c3`,
	`fo-ax`:`fo-ax`, `fo-ay`:`fo-ay`, `fo-az`:`fo-az`,
	`fo-bx`:`fo-bx`, `fo-by`:`fo-by`, `fo-bz`:`fo-bz`,
	`fo-cx`:`fo-cx`, `fo-cy`:`fo-cy`, `fo-cz`:`fo-cz`,
	`fo-dx`:`fo-dx`, `fo-dy`:`fo-dy`, `fo-dz`:`fo-dz`,
	`fo-ex`:`fo-ex`, `fo-ey`:`fo-ey`, `fo-ez`:`fo-ez`,
	`fo-fx`:`fo-fx`, `fo-fy`:`fo-fy`, `fo-fz`:`fo-fz`,
	`fo-{&(.test.a.x.1.y.0.z)}`:[]string{`fo-ax`,`fo-ay`,`fo-az`},
	`fo-{&(.test.b.x.1.y.0.z)}`:[]string{`fo-bx`,`fo-by`,`fo-bz`},
	`fo-{&(.test.b.x.2.y.0.z)}`:[]string{`fo-cx`,`fo-cy`,`fo-cz`},
	`fo-{&(.test.c.x.1.y.0.z)}`:[]string{`fo-dx`,`fo-dy`,`fo-dz`},
	`fo-{&(.test.c.x.2.y.0.z)}`:[]string{`fo-ex`,`fo-ey`,`fo-ez`},
	`fo-{&(.test.c.x.3.y.0.z)}`:[]string{`fo-fx`,`fo-fy`,`fo-fz`},
	`fo-{&(.test.⌜a b c⌟.x.⌜1 2 3⌟.y.0.z)}`:[]string{`fo-a1`,`fo-b2`,`fo-c3`},
	`foo-B`:`foo-B`,
	`foo-a`:`foo-a`,
	`foo-b`:`foo-b`,
	`foo-bar-xx-yy-zz`:`foo-bar-xx-yy-zz`,
	`foo.c++`:`foo.c++`,
	`foo.c`:`foo.c`,
	`foo.o`:`foo.o`,
	`foo.txt`:`foo.txt`,
	`foo/bar.o`:`foo/bar.o`,
	`foo/z.o`:`foo/z.o`,
	`foo_ab-$1-$2`:`foo_ab-{}-{}`,
	`foo_ab-a-b`:`foo_ab-a-b`,
	`foo_ab-aa-bb`:`foo_ab-aa-bb`,
	`foo_ab-ab-ba`:`foo_ab-ab-ba`,
	`foo_ab-xx-yy`:`foo_ab-xx-yy`,
	`foo_ab-xy-yx`:`foo_ab-xy-yx`,
	`foo_ab-{}{}-{}{}`:`foo_ab-{}{}-{}{}`,
	`foo_ba-$2-$1`:`foo_ba-{}-{}`,
	`foo_ba-b-a`:`foo_ba-b-a`,
	`foo_ba-ba-ab`:`foo_ba-ba-ab`,
	`foo_ba-bb-aa`:`foo_ba-bb-aa`,
	`foo_ba-yy-xx`:`foo_ba-yy-xx`,
	`foo_ba-{}{}-{}{}`:`foo_ba-{}{}-{}{}`,
	`fooa`:`fooa`, `foob`:`foob`, `fooc`:`fooc`,
	`foobar`:`foobar`, `not-foobar`:`not-foobar`,
	`mod-1`:`mod-1`,
	`skip-nil`:`skip-nil`,
	`test-B`:`test-B`,
	`test-a`:`test-a`,
	`test-b`:`test-b`,
	`test-foo-B`:`test-foo-B`,
	`test-foo-a`:`test-foo-a`,
	`test-foo-b`:`test-foo-b`,
	`test-foo`:`test-foo`,
	`test-mod-1`:`test-mod-1`,
	`test.paniconexit0`:`test.paniconexit0`,
	`test.timeout`:`test.timeout`,
	`test.txt`:`test.txt`,
	`v-x-y-z-{}-{}`:`v-x-y-z-{}-{}`,
	`v-x-y-{}-{}-{}`:`v-x-y-{}-{}-{}`,
	`v-x-{}-{}-{}-{}`:`v-x-{}-{}-{}-{}`,
	`v-{}-{}-{}-{}-{}`:`v-{}-{}-{}-{}-{}`, 
	`v1.h`:`v1.h`, `v2.h`:`v2.h`,
	`wy1{}zz`:`wy1{}zz`, `wy2{}zz`:`wy2{}zz`, `wy3{}zz`:`wy3{}zz`,
	`x&(something)`:`x{}`,
	`x-a`:`x-a`, `x-b`:`x-b`, `x-c`:`x-c`, `x-`:`x-`,
	`x-y-3-xyz`:`x-y-3-xyz`, // {=compound {21:36 {19:13 {=compound {19:46 {21:23:word x}} {=flag {=compound {19:52 {21:28:word y}} {=flag {19:58 {19:33:decimal 3}}}}}}}} {=flag {=compound {21:48 {21:23:word x}} {21:53 {21:28:word y}} {21:58 {21:33:word z}}}}}
	`x-y-3-xy{}`:`x-y-3-xy{}`, // {=compound {23:36 {19:13 {=compound {19:46 {1:9:word x}} {=flag {=compound {19:52 {1:9:word y}} {=flag {19:58 {19:33:decimal 3}}}}}}}} {=flag {=compound {23:48 {1:9:word x}} {23:53 {1:9:word y}} {23:58 {19:60:null}}}}}
	`x-y-3`:`x-y-3`, // {=compound {19:46 {1:9:word x}} {=flag {=compound {19:52 {1:9:word y}} {=flag {19:58 {19:33:decimal 3}}}}}}
	`x-y-z-{}-{}`:`x-y-z-{}-{}`,
	`x-y-{}-{}-{}`:`x-y-{}-{}-{}`,
	`x-{}-{}-{}-{}`:`x-{}-{}-{}-{}`,
	`x.c++`:`x.c++`, `y.c++`:`y.c++`,
	`x.gen`:`x.gen`, `y.gen`:`y.gen`, `z.gen`:`z.gen`,
	`x.h`:`x.h`, `x.o`:`x.o`, `y.o`:`y.o`,
	`x.o.a`:`x.o.a`, `x.o.b`:`x.o.b`, `x.o.c`:`x.o.c`,
	`x\,y\,z`:`x\,y\,z`,
	`xa`:`xa`, `xb`:`xb`, `xc`:`xc`,
	`xay1z`:`xay1z`, `xay2z`:`xay2z`, `xay3z`:`xay3z`,
	`xby1z`:`xby1z`, `xby2z`:`xby2z`, `xby3z`:`xby3z`,
	`xcy1z`:`xcy1z`, `xcy2z`:`xcy2z`, `xcy3z`:`xcy3z`,
	`xq`:`xq`, `xp`:`xp`, `xx`:`xx`, `xy`:`xy`, `yx`:`yx`, `yy`:`yy`, `yy-xx`:`yy-xx`,
	`xv1y.h`:`xv1y.h`,
	`xvw`:`xvw`, `xW{}{}`:`xW{}{}`, `W{}{}`:`W{}{}`,
	`xwy1{}zz`:`xwy1{}zz`, `xwy2{}zz`:`xwy2{}zz`, `xwy3{}zz`:`xwy3{}zz`,
	`xx-yy`:`xx-yy`, // {=compound {10:20:word xx} {=flag {10:23:word yy}}}
	`xxx-yyx`:`xxx-yyx`, // {=compound {6:18:word xxx} {=flag {6:22:word yyx}}}
	`xxx-yyy`:`xxx-yyy`, // {=compound {5:18:word xxx} {=flag {5:22:word yyy}}}
	`xx{}`:`xx{}`,
	`xy-yx`:`xy-yx`,
	`xyz`:`xyz`, // {=compound {21:48 {21:23:word x}} {21:53 {21:28:word y}} {21:58 {21:33:word z}}}
	`xy{}`:`xy{}`, // {=compound {23:48 {1:9:word x}} {23:53 {1:9:word y}} {23:58 {19:60:null}}}
	`x{&(.test.foreach.x)}`:`xvw`,
	`x{&(.test.foreach.x.3)}`:`xV{}{}`,
	`x{&(.test.foreach.x.4)}`:`xW{}{}`,
	`x{&(.test.h)}a`:`x-a`,
	`x{&(.test.h)}b`:`x-b`,
	`x{&(.test.h)}c`:`x-c`,
	`x{&(.test.xx)}a`: ``,
	`x{&(.test.xx)}b`: ``,
	`x{&(.test.xx)}c`: ``,
	`x{&(.test.z)}y1{}zz`:`xwy1{}zz`,
	`x{&(.test.z)}y2{}zz`:`xwy2{}zz`,
	`x{&(.test.z)}y3{}zz`:`xwy3{}zz`,
	`x{a b c}`:[]string{`xa`, `xb`, `xc`},
	`x{}`:`x{}`,
	`x{}aa`:`x{}aa`, `x{}bb`:`x{}bb`, `x{}cc`:`x{}cc`,
	`y-3`:`y-3`, // {=compound {19:52 {1:9:word y}} {=flag {19:58 {19:33:decimal 3}}}}
	`y-x-a`:`y-x-a`,
	`y-z-{}-{}`:`y-z-{}-{}`,
	`y-{}-{}-{}`:`y-{}-{}-{}`,
	`ya`:`ya`, `yb`:`yb`,
	`yxa`:`yxa`, `yxb`:`yxb`, `yxa-yxb`:`yxa-yxb`,
	`yy{}`:`yy{}`,
	`y{}`:`y{}`,
	`z-a`:`z-a`,
	`z-y-x-a`:`z-y-x-a`,
	`z-yxa-yxb`:`z-yxa-yxb`,
	`z-{}`:`z-{}`, `z-{}-{}`:`z-{}-{}`,
	`z.c`:`z.c`,
	`z{}`:`z{}`,
	`{}-3`:`{}-3`, // {=compound {19:52 {19:54:null}} {=flag {19:58 {19:33:decimal 3}}}}
	`{}-{}-3-{}{}{}`:`{}-{}-3-{}{}{}`, // {=compound {23:36 {19:13 {=compound {19:46 {19:48:null}} {=flag {=compound {19:52 {19:54:null}} {=flag {19:58 {19:33:decimal 3}}}}}}}} {=flag {=compound {23:48 {19:48:null}} {23:53 {19:54:null}} {23:58 {19:60:null}}}}}
	`{}-{}-3`:`{}-{}-3`, // {=compound {19:46 {19:48:null}} {=flag {=compound {19:52 {19:54:null}} {=flag {19:58 {19:33:decimal 3}}}}}}
	`{}-{}-{}`:`{}-{}-{}`, `{}-{}-{}-{}`:`{}-{}-{}-{}`, `{}-{}-{}-{}-{}`:`{}-{}-{}-{}-{}`,
	`{}-{}`:`{}-{}`, // {=compound {3:19 {3:20:null}} {=flag {3:22 {3:23:null}}}}
	`{}aa`:`{}aa`, `{}bb`:`{}bb`, `{}cc`:`{}cc`,
	`{}{}`:`{}{}`, `{}{}{}`:`{}{}{}`, `{}{}-{}{}`:`{}{}-{}{}`,
	`{}⌜foo bar⌟{}88`:`{}⌜foo bar⌟{}88`,
	`{}⌜foo bar⌟{}99`:`{}⌜foo bar⌟{}99`,
	`~1~`:`~1~`,
	`~2~`:`~2~`,
	`~a`:`~a`,
	`~b`:`~b`,
	`~c~`:`~c~`,
}
func check__string_com(ctx Context, _c *compound, _v Value) {
	var (
		k = sf("%v", _c)
		t = sf("%v", _v)
		v = checkpoints__string_com[k]
	)
	if v == nil {
		debug(pc(ctx,_c),
			_f("%v", ts(_c)),
			_f("%v", ts(_v)),
			_f("`%v`:`%v`,", _c, _v),
			trace{})
	} else {
		switch w := v.(type) {
		case []string: for _, v := range w { if t == v { return } }
		case   string:                       if t == w { return }
		}
		debug(pc(ctx,_c),
			_f("%v", ts(_c)),
			_f("%v", ts(_v)),
			_f(`%v → %v != %v ; %v`, _c, t, v, _c.elems),
			trace{})
	}
	return
}
